### ISSUE TITLE
Definir os papéis do SCRUM 

### ISSUE THREAD

**Issue by artur-seppa** [fga-eps-mds/2022-1-Squad3#15]
## Descrição

Separar e definir os papéis de SCRUM (Product Owner, Scrum Master, Arquiteto de Software e Desenvolvedor) entre os integrantes do time.

## Tarefas

- [x] Definir quem será o Product Owner
- [x] Definir quem será o Scrum Master
- [x] Definir quem será o Arquiteto de Software
- [x] Definir quem será o Desenvolvedor

## Critérios de Aceitação

- [x] Obter todos os papéis distribuídos no time.

**Comment by JoaoSchmitz** [comment]
**Product Owner**
- @charles-serafim
- @Julio-eng 

**Scrum Master**
- @Thiago-Cerq 
- @JoaoSchmitz 

**Arquiteto de Software**
- @kazpmcd 
- @Leonardo0o0

**Desenvolvedor**
- @macieljuniormax
- @artur-seppa
